# Generated by Django 5.1.1 on 2024-10-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_employee1_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee1',
            new_name='Employee',
        ),
    ]
