# Generated by Django 5.1.1 on 2024-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_employee_department_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
