# Generated by Django 5.1.1 on 2024-10-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_author_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
